### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by phoebedddd** [Nightmare-n/GraphRCNN#11]
Hello, how many Gpus did you use to train the KITTI data set, and how long did it take?

**Comment by NiranjanRavi1993** [comment]
Hi, how did you setup your KITTI dataset? I could not find instructions on the repo.

**Comment by Nightmare-n** [comment]
> Hello, how many Gpus did you use to train the KITTI data set, and how long did it take?

Graph-Vo costs about an hour of training time and 5G of GPU memory when trained on 4 A100 GPUs with 4 batch sizes per GPU.

**Comment by Nightmare-n** [comment]
> Hi, how did you setup your KITTI dataset? I could not find instructions on the repo.

Thanks for your interest! Code for the KITTI dataset will be released in the next few days at https://github.com/Nightmare-n/GD-MAE

**Comment by Nightmare-n** [comment]
Thanks for your patience! The code is available!

**Comment by phoebedddd** [comment]
> Thanks for your patience! The code is available!


> > Hello, how many Gpus did you use to train the KITTI data set, and how long did it take?
> 
> Graph-Vo costs about an hour of training time and 5G of GPU memory when trained on 4 A100 GPUs with 4 batch sizes per GPU.
Thank you very much for your reply!

**Comment by phoebedddd** [comment]
> > Hello, how many Gpus did you use to train the KITTI data set, and how long did it take?
> 
> Graph-Vo costs about an hour of training time and 5G of GPU memory when trained on 4 A100 GPUs with 4 batch sizes per GPU.

what about waymo dataset?Looking forward to your reply!Best wishes!
