### ISSUE TITLE
Pkl files

### ISSUE THREAD

**Issue by NiranjanRavi1993** [Nightmare-n/GraphRCNN#12]
Hi,
    Thank you for the repo. I have downloaded the waymo dataset and tried to run the pre-process code. However, I had a couple of questions, 
where can I find the below pkl files?

gt_database_1sweeps_withvelo/
│   │── dbinfos_train_1sweeps_withvelo.pkl
│   │── infos_train_01sweeps_filter_zero_gt.pkl
│   │── infos_val_01sweeps_filter_zero_gt.pkl

Also, it there any other checkpoint file needed to train the model? If so, how can i access it?

It would be helpful to get your inputs. 

Thank you
Regards
Niranjan Ravi.

**Comment by NiranjanRavi1993** [comment]
Please ignore the above question. create_data.py generated all pkl files. 

Where can I find this file:

https://github.com/Nightmare-n/GraphRCNN/blob/main/configs/waymo/voxelnet/two_stage/waymo_centerpoint_voxelnet_graphrcnn_6epoch_freeze.py#L22 

It would be helpful to get your inputs. 

Thank you.

**Comment by Nightmare-n** [comment]
Please send us an email and we will provide the checkpoint download link.
