### ISSUE TITLE
about kitti

### ISSUE THREAD

**Issue by phoebedddd** [Nightmare-n/GraphRCNN#14]
Can I directly transfer Kitti-related codes from GD-MAE code base to here for use? Is there anything that needs to be changed?

**Comment by Nightmare-n** [comment]
For the use of the KITTI dataset, you can refer to https://github.com/poodarchu/Det3D, but we recommend using GD-MAE directly to avoid some unexpected problems (e.g., different coordinate systems of different codebases).

**Comment by phoebedddd** [comment]
> KITTI数据集的使用可以参考https://github.com/poodarchu/Det3D，但是我们建议直接使用GD-MAE，避免一些意想不到的问题（例如，不同代码库的不同坐标系）。

Ok, I see. Thank you very much for your reply!Best wishes for you!
