### ISSUE TITLE
Is the repo now imcomplete?

### ISSUE THREAD

**Issue by synsin0** [Nightmare-n/GraphRCNN#3]
Thanks for your great work. I am intended to find related novel modules introduced in your paper but do not find these modules. Is this version of code complete and can reproduce the described accuracy in model_zoo.md?

**Comment by Nightmare-n** [comment]
Hi, the current code is incomplete, and the full code will be released in September.

**Comment by vehxianfish** [comment]
> Hi, the current code is incomplete, and the full code will be released in September.
@Nightmare-n,Thanks for your great work. Can you release code on KITTI dataset?

**Comment by Nightmare-n** [comment]
Thanks for your patience! The code is available!
