### ISSUE TITLE
Version of Waymo dataset

### ISSUE THREAD

**Issue by chun-hsueh-lee** [Nightmare-n/GraphRCNN#6]
Hi,

This is a very interesting repo and huge thanks for making it public.

I am trying to reproduce the result and I am confused about the version of waymo dataset you're using. 
![image](https://user-images.githubusercontent.com/112966419/193629622-08dbe283-19bb-4269-bcf3-0513d1451fd6.png)
There are several versions of dataset on the website, could you please provide more details about the version that is used in this repo?

Thank you so much!

**Comment by Nightmare-n** [comment]
Hi, we use v1.2 for the experiment.
