### ISSUE TITLE
Can not find pkl files

### ISSUE THREAD

**Issue by seanwcy** [Nightmare-n/GraphRCNN#7]
HELLO ,I can not find the pkl file in waymo datasets,so where can i find it ,thanks

**Comment by Nightmare-n** [comment]
Hi, you could follow the `Data Preparation` section to generate pkl files.

**Comment by seanwcy** [comment]
作者您好，我是否需要将training训练集0-31全部下载下来，以及val训练集0-7全部下载下来

**Comment by Nightmare-n** [comment]
需要的

**Comment by imagingzzy** [comment]
您好，请问可以提供一下预训练好的模型吗?

**Comment by Nightmare-n** [comment]
> 您好，请问可以提供一下预训练好的模型吗?

可以的，发我一封邮件，我会提供下载链接
